export const menucategories = [
  {
    id: "men",
    label: "Men",
    categories: [
      {
        id: "topwear",
        label: "Topwear",
        options: [
          { id: "tshirts", label: "T-Shirts" },
          { id: "casual-shirts", label: "Casual Shirts" },
          { id: "formal-shirts", label: "Formal Shirts" },
          { id: "sweatshirts", label: "Sweatshirts" },
          { id: "sweaters", label: "Sweaters" },
          { id: "jackets", label: "Jackets" },
          { id: "blazers-coats", label: "Blazers & Coats" },
          { id: "suits", label: "Suits" },
          { id: "rain-jackets", label: "Rain Jackets" },
        ],
      },
      {
        id: "indian-festive",
        label: "Indian & Festive Wear",
        options: [
          { id: "kurtas-kurta-sets", label: "Kurtas & Kurta Sets" },
          { id: "sherwanis", label: "Sherwanis" },
          { id: "nehru-jackets", label: "Nehru Jackets" },
          { id: "dhotis", label: "Dhotis" },
        ],
      },
      {
        id: "bottomwear",
        label: "Bottomwear",
        options: [
          { id: "jeans", label: "Jeans" },
          { id: "casual-trousers", label: "Casual Trousers" },
          { id: "formal-trousers", label: "Formal Trousers" },
          { id: "shorts", label: "Shorts" },
          { id: "trackpants-joggers", label: "Track Pants & Joggers" },
        ],
      },
      {
        id: "innerwear-sleepwear",
        label: "Innerwear & Sleepwear",
        options: [
          { id: "briefs-trunks", label: "Briefs & Trunks" },
          { id: "boxers", label: "Boxers" },
          { id: "vests", label: "Vests" },
          { id: "sleepwear", label: "Sleepwear & Loungewear" },
          { id: "thermals", label: "Thermals" },
        ],
      },
      {
        id: "plus-size",
        label: "Plus Size",
        options: [],
      },
      {
        id: "footwear",
        label: "Footwear",
        options: [
          { id: "casual-shoes", label: "Casual Shoes" },
          { id: "sports-shoes", label: "Sports Shoes" },
          { id: "formal-shoes", label: "Formal Shoes" },
          { id: "sneakers", label: "Sneakers" },
          { id: "sandals-floaters", label: "Sandals & Floaters" },
          { id: "flipflops", label: "Flip Flops" },
          { id: "socks", label: "Socks" },
        ],
      },
      {
        id: "sports-activewear",
        label: "Sports & Active Wear",
        options: [
          { id: "sports-shoes", label: "Sports Shoes" },
          { id: "sports-sandals", label: "Sports Sandals" },
          { id: "active-tshirts", label: "Active T-Shirts" },
          { id: "trackpants-shorts", label: "Track Pants & Shorts" },
          { id: "tracksuits", label: "Tracksuits" },
          { id: "jackets-sweatshirts", label: "Jackets & Sweatshirts" },
          { id: "sports-accessories", label: "Sports Accessories" },
          { id: "swimwear", label: "Swimwear" },
        ],
      },
      {
        id: "gadgets",
        label: "Gadgets",
        options: [
          { id: "smart-wearables", label: "Smart Wearables" },
          { id: "fitness-gadgets", label: "Fitness Gadgets" },
          { id: "headphones", label: "Headphones" },
          { id: "speakers", label: "Speakers" },
        ],
      },
      {
        id: "fashion-accessories",
        label: "Fashion Accessories",
        options: [
          { id: "wallets", label: "Wallets" },
          { id: "belts", label: "Belts" },
          { id: "perfumes", label: "Perfumes & Body Mists" },
          { id: "trimmers", label: "Trimmers" },
          { id: "deodorants", label: "Deodorants" },
          { id: "ties-cufflinks", label: "Ties, Cufflinks & Pocket Squares" },
          { id: "gift-sets", label: "Accessory Gift Sets" },
          { id: "caps-hats", label: "Caps & Hats" },
          { id: "mufflers-scarves", label: "Mufflers, Scarves & Gloves" },
          { id: "phone-cases", label: "Phone Cases" },
          { id: "rings-wristwear", label: "Rings & Wristwear" },
          { id: "helmets", label: "Helmets" },
        ],
      },
      {
        id: "bags-backpacks",
        label: "Bags & Backpacks",
        options: [],
      },
      {
        id: "luggage-trolleys",
        label: "Luggages & Trolleys",
        options: [],
      },
      {
        id: "personal-care",
        label: "Personal Care & Grooming",
        options: [],
      },
      {
        id: "sunglasses-frames",
        label: "Sunglasses & Frames",
        options: [],
      },
      {
        id: "watches",
        label: "Watches",
        options: [],
      },
    ],
  },
  {
    id: "women",
    label: "Women",
    categories: [
      {
        id: "ethnicwear",
        label: "Indian & Fusion Wear",
        options: [
          { id: "kurtas-suits", label: "Kurtas & Suits" },
          { id: "kurti-tunics-tops", label: "Kurtis, Tunics & Tops" },
          { id: "sarees", label: "Sarees" },
          { id: "ethnic-wear", label: "Ethnic Wear" },
          {
            id: "leggings-salwars-churidars",
            label: "Leggings, Salwars & Churidars",
          },
          { id: "skirts-palazzos", label: "Skirts & Palazzos" },
          { id: "dress-materials", label: "Dress Materials" },
          { id: "lehenga-cholis", label: "Lehenga Cholis" },
          { id: "dupattas-shawls", label: "Dupattas & Shawls" },
          { id: "jackets", label: "Jackets" },
        ],
      },
      {
        id: "westernwear",
        label: "Western Wear",
        options: [
          { id: "dresses", label: "Dresses" },
          { id: "tops", label: "Tops" },
          { id: "tshirts", label: "T-shirts" },
          { id: "jeans", label: "Jeans" },
          { id: "trousers-capris", label: "Trousers & Capris" },
          { id: "shorts-skirts", label: "Shorts & Skirts" },
          { id: "co-ords", label: "Co-ords" },
          { id: "playsuits", label: "Playsuits" },
          { id: "jumpsuits", label: "Jumpsuits" },
          { id: "shrugs", label: "Shrugs" },
          { id: "sweaters-sweatshirts", label: "Sweaters & Sweatshirts" },
          { id: "jackets-coats", label: "Jackets & Coats" },
          { id: "blazers-waistcoats", label: "Blazers & Waistcoats" },
        ],
      },
      {
        id: "maternity",
        label: "Maternity",
        options: [],
      },
      {
        id: "footwear",
        label: "Footwear",
        options: [
          { id: "flats", label: "Flats" },
          { id: "casual-shoes", label: "Casual Shoes" },
          { id: "heels", label: "Heels" },
          { id: "boots", label: "Boots" },
          { id: "sports-shoes", label: "Sports Shoes & Floaters" },
        ],
      },
      {
        id: "lingerie-sleepwear",
        label: "Lingerie & Sleepwear",
        options: [
          { id: "bras", label: "Bra" },
          { id: "briefs", label: "Briefs" },
          { id: "shapewear", label: "Shapewear" },
          { id: "sleepwear-loungewear", label: "Sleepwear & Loungewear" },
          { id: "swimwear", label: "Swimwear" },
          { id: "camisoles-thermals", label: "Camisoles & Thermals" },
        ],
      },
      {
        id: "beauty-personal-care",
        label: "Beauty & Personal Care",
        options: [
          { id: "makeup", label: "Makeup" },
          { id: "skincare", label: "Skincare" },
          { id: "premium-beauty", label: "Premium Beauty" },
          { id: "lipsticks", label: "Lipsticks" },
          { id: "fragrances", label: "Fragrances" },
        ],
      },
      {
        id: "gadgets",
        label: "Gadgets",
        options: [
          { id: "smart-wearables", label: "Smart Wearables" },
          { id: "fitness-gadgets", label: "Fitness Gadgets" },
          { id: "headphones", label: "Headphones" },
          { id: "speakers", label: "Speakers" },
        ],
      },
      {
        id: "jewellery",
        label: "Jewellery",
        options: [
          { id: "fashion-jewellery", label: "Fashion Jewellery" },
          { id: "fine-jewellery", label: "Fine Jewellery" },
          { id: "earrings", label: "Earrings" },
        ],
      },
      {
        id: "bags-accessories",
        label: "Backpacks & Handbags",
        options: [
          { id: "backpacks", label: "Backpacks" },
          { id: "handbags-wallets", label: "Handbags, Bags & Wallets" },
          { id: "luggages-trolleys", label: "Luggages & Trolleys" },
        ],
      },
      {
        id: "plus-size",
        label: "Plus Size",
        options: [],
      },
    ],
  },
  {
    id: "kids",
    label: "Kids",
    categories: [
      {
        id: "boys-clothing",
        label: "Boys Clothing",
        options: [
          { id: "tshirts", label: "T-Shirts" },
          { id: "shirts", label: "Shirts" },
          { id: "shorts", label: "Shorts" },
          { id: "jeans", label: "Jeans" },
          { id: "trousers", label: "Trousers" },
          { id: "clothing-sets", label: "Clothing Sets" },
          { id: "ethnic-wear", label: "Ethnic Wear" },
          { id: "track-pants-pyjamas", label: "Track Pants & Pyjamas" },
          {
            id: "jackets-sweaters-sweatshirts",
            label: "Jacket, Sweater & Sweatshirts",
          },
          { id: "party-wear", label: "Party Wear" },
          { id: "innerwear-thermals", label: "Innerwear & Thermals" },
          { id: "nightwear-loungewear", label: "Nightwear & Loungewear" },
          { id: "value-packs", label: "Value Packs" },
        ],
      },
      {
        id: "girls-clothing",
        label: "Girls Clothing",
        options: [
          { id: "dresses", label: "Dresses" },
          { id: "tops", label: "Tops" },
          { id: "tshirts", label: "T-Shirts" },
          { id: "clothing-sets", label: "Clothing Sets" },
          { id: "lehenga-choli", label: "Lehenga Choli" },
          { id: "kurta-sets", label: "Kurta Sets" },
          { id: "party-wear", label: "Party Wear" },
          { id: "dungarees-jumpsuits", label: "Dungarees & Jumpsuits" },
          { id: "skirts-shorts", label: "Skirts & Shorts" },
          { id: "tights-leggings", label: "Tights & Leggings" },
          { id: "jeans-trousers-capris", label: "Jeans, Trousers & Capris" },
          {
            id: "jackets-sweaters-sweatshirts",
            label: "Jacket, Sweater & Sweatshirts",
          },
          { id: "innerwear-thermals", label: "Innerwear & Thermals" },
          { id: "nightwear-loungewear", label: "Nightwear & Loungewear" },
          { id: "value-packs", label: "Value Packs" },
        ],
      },
      {
        id: "footwear",
        label: "Footwear",
        options: [
          { id: "casual-shoes", label: "Casual Shoes" },
          { id: "flipflops", label: "Flipflops" },
          { id: "sports-shoes", label: "Sports Shoes" },
          { id: "flats", label: "Flats" },
          { id: "sandals", label: "Sandals" },
          { id: "heels", label: "Heels" },
          { id: "school-shoes", label: "School Shoes" },
          { id: "socks", label: "Socks" },
        ],
      },
      {
        id: "toys-games",
        label: "Toys & Games",
        options: [
          { id: "learning-development", label: "Learning & Development" },
          { id: "activity-toys", label: "Activity Toys" },
          { id: "soft-toys", label: "Soft Toys" },
          { id: "action-figures-playset", label: "Action Figures / Play Set" },
        ],
      },
      {
        id: "infants",
        label: "Infants",
        options: [
          { id: "bodysuits", label: "Bodysuits" },
          { id: "rompers-sleepsuits", label: "Rompers & Sleepsuits" },
          { id: "clothing-sets", label: "Clothing Sets" },
          { id: "tshirts-tops", label: "T-shirts & Tops" },
          { id: "dresses", label: "Dresses" },
          { id: "bottom-wear", label: "Bottom Wear" },
          { id: "winter-wear", label: "Winter Wear" },
          { id: "innerwear-sleepwear", label: "Innerwear & Sleepwear" },
          { id: "infant-care", label: "Infant Care" },
        ],
      },
      {
        id: "kids-accessories",
        label: "Kids Accessories",
        options: [
          { id: "bags-backpacks", label: "Bags & Backpacks" },
          { id: "watches", label: "Watches" },
          {
            id: "jewellery-hair-accessory",
            label: "Jewellery & Hair Accessories",
          },
          { id: "sunglasses", label: "Sunglasses" },
          { id: "masks-protective-gears", label: "Masks & Protective Gears" },
          { id: "caps-hats", label: "Caps & Hats" },
        ],
      },
      {
        id: "home-bath",
        label: "Home & Bath",
        options: [],
      },
      {
        id: "personal-care",
        label: "Personal Care",
        options: [],
      },
      {
        id: "brands",
        label: "Brands",
        options: [
          { id: "hm", label: "H&M" },
          { id: "max-kids", label: "Max Kids" },
          { id: "pantaloon", label: "Pantaloon" },
          {
            id: "united-colors-beneton",
            label: "United Colors Of Benetton Kids",
          },
          { id: "yk", label: "YK" },
          { id: "us-polo-kids", label: "U.S. Polo Assn. Kids" },
          { id: "mothercare", label: "Mothercare" },
          { id: "hrx", label: "HRX" },
        ],
      },
    ],
  },
  {
    id: "home",
    label: "Home",
    categories: [
      {
        id: "bed-linen-furnishing",
        label: "Bed Linen & Furnishing",
        options: [
          { id: "bed-runners", label: "Bed Runners" },
          { id: "mattress-protectors", label: "Mattress Protectors" },
          { id: "bedsheets", label: "Bedsheets" },
          { id: "bedding-sets", label: "Bedding Sets" },
          { id: "blankets-quilts-dohars", label: "Blankets, Quilts & Dohars" },
          { id: "pillows-pillow-covers", label: "Pillows & Pillow Covers" },
          { id: "bed-covers", label: "Bed Covers" },
          { id: "diwan-sets", label: "Diwan Sets" },
          { id: "chair-pads-covers", label: "Chair Pads & Covers" },
          { id: "sofa-covers", label: "Sofa Covers" },
        ],
      },
      {
        id: "bath",
        label: "Bath",
        options: [
          { id: "bath-towels", label: "Bath Towels" },
          { id: "hand-face-towels", label: "Hand & Face Towels" },
          { id: "beach-towels", label: "Beach Towels" },
          { id: "towels-set", label: "Towels Set" },
          { id: "bath-rugs", label: "Bath Rugs" },
          { id: "bath-robes", label: "Bath Robes" },
          { id: "bathroom-accessories", label: "Bathroom Accessories" },
          { id: "shower-curtains", label: "Shower Curtains" },
        ],
      },
      {
        id: "home-decor",
        label: "Home Décor",
        options: [
          { id: "plants-planters", label: "Plants & Planters" },
          { id: "aromas-candles", label: "Aromas & Candles" },
          { id: "clocks", label: "Clocks" },
          { id: "mirrors", label: "Mirrors" },
          { id: "wall-decor", label: "Wall Décor" },
          { id: "festive-decor", label: "Festive Decor" },
          { id: "pooja-essentials", label: "Pooja Essentials" },
          { id: "wall-shelves", label: "Wall Shelves" },
          { id: "fountains", label: "Fountains" },
          { id: "showpieces-vases", label: "Showpieces & Vases" },
          { id: "ottoman", label: "Ottoman" },
        ],
      },
      {
        id: "furniture",
        label: "Furniture",
        options: [],
      },
      {
        id: "home-gift-sets",
        label: "Home Gift Sets",
        options: [],
      },
      {
        id: "kitchen-table",
        label: "Kitchen & Table",
        options: [
          { id: "table-runners", label: "Table Runners" },
          { id: "dinnerware-serveware", label: "Dinnerware & Serveware" },
          { id: "cups-mugs", label: "Cups and Mugs" },
          { id: "bakeware-cookware", label: "Bakeware & Cookware" },
          { id: "kitchen-storage-tools", label: "Kitchen Storage & Tools" },
          { id: "bar-drinkware", label: "Bar & Drinkware" },
          {
            id: "table-covers-furnishings",
            label: "Table Covers & Furnishings",
          },
        ],
      },
      {
        id: "storage",
        label: "Storage",
        options: [
          { id: "bins", label: "Bins" },
          { id: "hangers", label: "Hangers" },
          { id: "organisers", label: "Organisers" },
          { id: "hooks-holders", label: "Hooks & Holders" },
          { id: "laundry-bags", label: "Laundry Bags" },
        ],
      },
    ],
  },
];
