export const productsData = {
  "Boston Premium TShirt": {
    _id: "6436b7483ba11401fd5a6c6c",
    productId: "boston-premium-tshirt",
    title: "Boston Premium TShirt",
    desc: "This TShirt is specially designed to long last and endure high intensity training. Built for real men.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9oXzfDkZkBH6Sr0V5gxEupg3FBZQnnC_UQA&usqp=CAU",
    category: "T-shirt",
    size: ["L", "M", "S", "XL", "XXL"],
    color: ["red", "blue", "GREEN"],
    price: 1,
    availableQty: 4,
    createdAt: "2023-04-12T13:51:04.561Z",
    updatedAt: "2023-07-01T11:16:39.980Z",
    __v: 0,
  },
  "Classic White Tee": {
    _id: "6436b7483ba11401fd5a6c6f",
    productId: "classic-white-tee-2",
    title: "Classic White Tee",
    desc: "This t-shirt is a wardrobe staple, perfect for any occasion. Made from high-quality cotton, it's soft, comfortable, and durable. The classic white color makes it easy to pair with any outfit.",
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQT7jxkF--Rdsj4BlZq0mZdaCrxCLLOdh36jQNhpp0HZaraldqr-HT_Qy0JDhte5MTPinuv1LVBE2lResjDx3rD96e9bXh0tpfqTyGz9E8C8CO-q1wNiA-1n3DllZ-DMDhWTQ&usqp=CAc",
    category: "T-shirt",
    size: ["L"],
    color: ["White"],
    price: 499,
    availableQty: 1,
    createdAt: "2023-04-12T13:51:04.634Z",
    updatedAt: "2023-04-19T10:09:39.689Z",
    __v: 0,
  },
  "Graphic Black Tee": {
    _id: "6436b7483ba11401fd5a6c71",
    productId: "graphic-black-tee",
    title: "Graphic Black Tee",
    desc: "Make a statement with this bold and edgy t-shirt. The black fabric provides a sleek backdrop for the eye-catching graphic design, which features intricate details and vibrant colors. The slim fit cut is flattering and modern.",
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQJuNPyRKHnK0ymROjojvSjNFSgsmJTtX-lE8MK40v3gC8WVOJFdSFGJCpgRnPsclXHnQaLbXjsGe5yhW71fQIBzCaoHW5fAGZ11979BOdCoILLf1ZvsqGt&usqp=CAc",
    category: "T-shirt",
    size: [],
    color: [],
    price: 499,
    availableQty: 0,
    createdAt: "2023-04-12T13:51:04.704Z",
    updatedAt: "2023-04-21T13:44:02.215Z",
    __v: 0,
  },
  "Tie-Dye Tee": {
    _id: "6436b7483ba11401fd5a6c73",
    productId: "tie-dye-tee",
    title: "Tie-Dye Tee",
    desc: "Add some fun and personality to your wardrobe with this groovy tie-dye t-shirt. Each shirt is unique, with a one-of-a-kind pattern of bright, bold colors. The loose fit and breathable fabric make it perfect for outdoor activities and sunny days.",
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSZY9YEGmtnUSe3wlRosQhHHwV6L8jfZCcvq4WY3HIr2SFsddsPtjq44ahFGnyvaimZ_vIvXpLn8pSHvfrzmjMvoUqmWvYGbKVvklE9DT1QGFrrAZnabPKFdirnIbrAw33Zv870&usqp=CAc",
    category: "T-shirt",
    size: ["S"],
    color: ["Grey"],
    price: 499,
    availableQty: 1,
    createdAt: "2023-04-12T13:51:04.775Z",
    updatedAt: "2023-04-12T13:51:04.775Z",
    __v: 0,
  },
  "Minimalist Navy Tee": {
    _id: "6436b7483ba11401fd5a6c75",
    productId: "minimalist-navy-tee",
    title: "Minimalist Navy Tee",
    desc: "This t-shirt is the epitome of understated cool. The navy blue color is classic and versatile, while the clean and simple text design adds just the right amount of interest. The lightweight fabric is perfect for layering or wearing on its own.",
    img: "https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1680683233_4058586.jpg?format=webp&w=480&dpr=1.8",
    category: "T-shirt",
    size: ["L"],
    color: ["White"],
    price: 499,
    availableQty: 1,
    createdAt: "2023-04-12T13:51:04.845Z",
    updatedAt: "2023-04-12T13:51:04.845Z",
    __v: 0,
  },
  "Floral Pink Tee": {
    _id: "6436b7483ba11401fd5a6c77",
    productId: "floral-pink-tee",
    title: "Floral Pink Tee",
    desc: "Bring a touch of femininity to your wardrobe with this pretty t-shirt. The soft pink hue is flattering on any skin tone, while the delicate floral print adds a whimsical touch. The relaxed fit and soft cotton material make it a comfortable choice for all-day wear.",
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQjB-FsjdCxB64Py3ZaxKNxuppZPL9Lumyx7S6fPSmL2lCHMOyQDWgNrVF-nyRRNXRyB2Bdw58MoiWJ_OEtbZlmEt9BuZh_fZgV2y07QzEldlQpykalRx-EZmcnsYXnC6GXUA&usqp=CAc",
    category: "T-shirt",
    size: ["XL"],
    color: ["Black"],
    price: 499,
    availableQty: 1,
    createdAt: "2023-04-12T13:51:04.915Z",
    updatedAt: "2023-04-12T13:51:04.915Z",
    __v: 0,
  },
  "Solid Green TShirt": {
    _id: "6436bcc83ba11401fd5a6ca3",
    productId: "Solid-green-tshirt",
    title: "Solid Green TShirt",
    desc: "This TShirt is specially designed to long last and endure high intensity training. Built for real men.",
    img: "https://prod-img.thesouledstore.com/public/theSoul/uploads/catalog/product/1654764857_3948620.jpg?format=webp&w=480&dpr=1.8",
    category: "T-shirt",
    size: [],
    color: [],
    price: 499,
    availableQty: 0,
    createdAt: "2023-04-12T14:14:32.414Z",
    updatedAt: "2023-04-22T11:42:01.751Z",
    __v: 0,
  },
};

export const filtersOption = [
  {
    id: 1,
    label: "Categories",
    options: [
      { id: "casual-tshirt", label: "Casual T-Shirts" },
      { id: "t-shirts", label: "T-Shirts" },
      { id: "polo", label: "Polo T-Shirts" },
      { id: "shirts", label: "Shirts" },
      { id: "jeans", label: "Jeans" },
      { id: "jackets", label: "Jackets" },
      { id: "type", label: "Type" },
    ],
  },
  {
    id: 4,
    label: "Brands",
    options: [
      { id: "nike", label: "Nike" },
      { id: "adidas", label: "Adidas" },
      { id: "puma", label: "Puma" },
      { id: "levis", label: "Levi's" },
      { id: "zara", label: "Zara" },
    ],
  },
  {
    id: 6,
    label: "Color",
    options: [
      { id: "black", label: "Black", color: "#000000" },
      { id: "white", label: "White", color: "#FFFFFF" },
      { id: "blue", label: "Blue", color: "#0000FF" },
      { id: "red", label: "Red", color: "#FF0000" },
      { id: "gren", label: "Green", color: "#008000" },
      { id: "yellow", label: "Yellow", color: "#FFFF00" },
      { id: "orange", label: "Orange", color: "#FFA500" },
      { id: "purple", label: "Purple", color: "#800080" },
      { id: "pink", label: "Pink", color: "#FFC0CB" },
      { id: "gray", label: "Gray", color: "#808080" },
      { id: "brown", label: "Brown", color: "#A52A2A" },
      { id: "cyan", label: "Cyan", color: "#00FFFF" },
    ],
  },
  {
    id: 7,
    label: "Discount",
    options: [
      {
        id: 10,
        label: "10% and above",
      },
      {
        id: 20,
        label: "20% and above",
      },
      {
        id: 30,
        label: "30% and above",
      },
      {
        id: 40,
        label: "40% and above",
      },
      {
        id: 50,
        label: "50% and above",
      },
      {
        id: 60,
        label: "60% and above",
      },
      {
        id: 70,
        label: "70% and above",
      },
      {
        id: 80,
        label: "80% and above",
      },
    ],
  },
];
