import formidable from "formidable";
import fs from "fs";
import csv from "csv-parser";
import connectDB from "@/middleware/conn";
import Commodity from "@/models/Commodity";

export const config = {
  api: {
    bodyParser: false,
  },
};

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  await connectDB();

  const form = formidable({ multiples: false, keepExtensions: true });

  form.parse(req, async (err, fields, files) => {
    if (err) {
      return res.status(500).json({ error: "File parsing failed" });
    }

    try {
      const file = Array.isArray(files.csvFile)
        ? files.csvFile[0]
        : files.csvFile;

      if (!file || !file.filepath) {
        return res.status(400).json({ error: "No file uploaded" });
      }

      const results = [];
      await new Promise((resolve, reject) => {
        fs.createReadStream(file.filepath)
          .pipe(csv())
          .on("data", (row) => results.push(row))
          .on("end", resolve)
          .on("error", reject);
      });

      // 🔹 Transform CSV rows into schema-compliant objects
      const docs = results.map((row) => {
        return {
          sku: row.sku, // Your hook will use this, or generate one if it's empty/missing
          name: row.name,
          description: row.description,
          category: row.category || "",
          variants: row.variants ? JSON.parse(row.variants) : [],
          // --- We no longer pass 'slug' ---
          // 'slug' will be auto-generated by the pre('validate') hook
        };
      });

      if (docs.length > 0) {
        // --- THIS IS THE KEY CHANGE ---
        // Use Model.create() to trigger the Mongoose hooks
        const createdCommodities = await Commodity.create(docs);
        res.status(200).json({ inserted: createdCommodities.length });
      } else {
        res.status(200).json({ inserted: 0 });
      }
    } catch (e) {
      console.error("Upload error:", e);
      // This will now catch duplicate SKU errors or other validation errors
      if (e.code === 11000) {
        return res
          .status(400)
          .json({ error: "One or more SKUs in the CSV already exist." });
      }
      res.status(500).json({ error: e.message });
    }
  });
}
